name: Generating Distributions
run-name: Generating Distributions for changes made by @${{ github.actor }}
on: [push]

jobs:
    Base:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Building AmpTools
              run: |
                mkdir Tutorials/Dalitz/lib
                mkdir Tutorials/Dalitz/bin
                make
                export AMPTOOLS_HOME=$(pwd)
                echo "AMPTOOLS_HOME=$AMPTOOLS_HOME" >> $GITHUB_ENV
                echo "AMPTOOLS=$AMPTOOLS_HOME/AmpTools" >> $GITHUB_ENV
                echo "AMPPLOTTER=$AMPTOOLS_HOME/AmpPlotter" >> $GITHUB_ENV
                echo "DALITZ=$AMPTOOLS_HOME/Tutorials/Dalitz" >> $GITHUB_ENV
                echo "UNIT_TESTS=$AMPTOOLS_HOME/UnitTests" >> $GITHUB_ENV
            - name: Generating Distributions
              run: |
                cd $UNIT_TESTS
                $DALITZ/bin/generatePhaseSpace phasespace.gen.root 100000 12345
                $DALITZ/bin/toyAcceptance phasespace.gen.root phasespace.acc.root 12345
                $DALITZ/bin/generatePhysics parserTest.cfg physics.gen.root 100000 12345
                $DALITZ/bin/toyAcceptance physics.gen.root physics.acc.root 12345
                $DALITZ/bin/fitAmplitudes parserTest.cfg
                ./distributions
            - name: Committing changes
              run: |
                git config --local user.email "action@github.com"	                
                git config --local user.name "github-actions"
                cd $UNIT_TESTS
                cd models
                mv distFile.cfg distBase.cfg
                git add distBase.cfg
                git commit -m "Added Distributions" 
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}

    MPI:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Building AmpTools
              run: |
                mkdir Tutorials/Dalitz/lib
                mkdir Tutorials/Dalitz/bin
                make mpi
                export AMPTOOLS_HOME=$(pwd)
                echo "AMPTOOLS_HOME=$AMPTOOLS_HOME" >> $GITHUB_ENV
                echo "AMPTOOLS=$AMPTOOLS_HOME/AmpTools" >> $GITHUB_ENV
                echo "AMPPLOTTER=$AMPTOOLS_HOME/AmpPlotter" >> $GITHUB_ENV
                echo "DALITZ=$AMPTOOLS_HOME/Tutorials/Dalitz" >> $GITHUB_ENV
                echo "UNIT_TESTS=$AMPTOOLS_HOME/UnitTests" >> $GITHUB_ENV
            - name: ConfigFileParser
              if: success() || failure()
              run: |
                cd $UNIT_TESTS
                $DALITZ/bin/generatePhaseSpace phasespace.gen.root 100000 12345
                $DALITZ/bin/toyAcceptance phasespace.gen.root phasespace.acc.root 12345
                $DALITZ/bin/generatePhysics parserTest.cfg physics.gen.root 100000 12345
                $DALITZ/bin/toyAcceptance physics.gen.root physics.acc.root 12345
                $DALITZ/bin/fitAmplitudes parserTest.cfg
                mpirun -n 3 ./distributionsMPI
            - name: Committing changes
              run: |
                git config --local user.email "action@github.com"	                
                git config --local user.name "github-actions"
                cd $UNIT_TESTS
                cd models
                mv distFile.cfg distMPI.cfg
                git add distMPI.cfg
                git commit -m "Added Distributions" 
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}


    GPU:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Building AmpTools
              run: |
                mkdir Tutorials/Dalitz/lib
                mkdir Tutorials/Dalitz/bin
                make gpu
                export AMPTOOLS_HOME=$(pwd)
                echo "AMPTOOLS_HOME=$AMPTOOLS_HOME" >> $GITHUB_ENV
                echo "AMPTOOLS=$AMPTOOLS_HOME/AmpTools" >> $GITHUB_ENV
                echo "AMPPLOTTER=$AMPTOOLS_HOME/AmpPlotter" >> $GITHUB_ENV
                echo "DALITZ=$AMPTOOLS_HOME/Tutorials/Dalitz" >> $GITHUB_ENV
                echo "UNIT_TESTS=$AMPTOOLS_HOME/UnitTests" >> $GITHUB_ENV
            - name: ConfigFileParser
              if: success() || failure()
              run: |
                cd $UNIT_TESTS
                $DALITZ/bin/generatePhaseSpace_GPU phasespace.gen.root 100000 12345
                $DALITZ/bin/toyAcceptance_GPU phasespace.gen.root phasespace.acc.root 12345
                $DALITZ/bin/generatePhysics_GPU parserTest.cfg physics.gen.root 100000 12345
                $DALITZ/bin/toyAcceptance_GPU physics.gen.root physics.acc.root 12345
                $DALITZ/bin/fitAmplitudes_GPU parserTest.cfg
                ./distributions_GPU
            - name: Committing changes
              run: |
                git config --local user.email "action@github.com"	                
                git config --local user.name "github-actions"
                cd $UNIT_TESTS
                cd models
                mv distFile.cfg distGPU.cfg
                git add distGPU.cfg
                git commit -m "Added Distributions" 
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}

    MPI-GPU:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Building AmpTools
              run: |
                mkdir Tutorials/Dalitz/lib
                mkdir Tutorials/Dalitz/bin
                make mpigpu
                export AMPTOOLS_HOME=$(pwd)
                echo "AMPTOOLS_HOME=$AMPTOOLS_HOME" >> $GITHUB_ENV
                echo "AMPTOOLS=$AMPTOOLS_HOME/AmpTools" >> $GITHUB_ENV
                echo "AMPPLOTTER=$AMPTOOLS_HOME/AmpPlotter" >> $GITHUB_ENV
                echo "DALITZ=$AMPTOOLS_HOME/Tutorials/Dalitz" >> $GITHUB_ENV
                echo "UNIT_TESTS=$AMPTOOLS_HOME/UnitTests" >> $GITHUB_ENV
            - name: ConfigFileParser
              if: success() || failure()
              run: |
                cd $UNIT_TESTS
                $DALITZ/bin/generatePhaseSpace_GPU phasespace.gen.root 100000 12345
                $DALITZ/bin/toyAcceptance_GPU phasespace.gen.root phasespace.acc.root 12345
                $DALITZ/bin/generatePhysics_GPU parserTest.cfg physics.gen.root 100000 12345
                $DALITZ/bin/toyAcceptance_GPU physics.gen.root physics.acc.root 12345
                mpirun -n 3 $DALITZ/bin/fitAmplitudesMPI_GPU parserTest.cfg
                mpirun -n 3 ./distributionsMPI_GPU
            - name: Committing changes
              run: |
                git config --local user.email "action@github.com"	                
                git config --local user.name "github-actions"
                cd $UNIT_TESTS
                cd models
                mv distFile.cfg distMPIGPU.cfg
                git add distMPIGPU.cfg
                git commit -m "Added Distributions" 
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
