name: Install ROOT
on: 
    workflow_call:
        outputs:
            ROOTSYS:
              description: "The path to ROOTSYS"
              value: ${{ jobs.install-root.outputs.ROOTSYS }}
jobs:
    install-root:
        runs-on: ubuntu-latest
        outputs:
            ROOTSYS: ${{ steps.step2.outputs.ROOTSYS }}
        steps:
            - name: Install Dependencies
              id: step1
              run: |
                sudo apt-get update
                sudo apt-get install -y binutils cmake dpkg-dev g++ gcc libssl-dev git libx11-dev libxext-dev libxft-dev libxpm-dev python3 libtbb-dev gfortran libpcre3-dev libglu1-mesa-dev libglew-dev libftgl-dev libfftw3-dev libcfitsio-dev libgraphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python3-dev python3-numpy libxml2-dev libkrb5-dev libgsl-dev qtwebengine5-dev nlohmann-json3-dev libmysqlclient-dev
            - name: Install ROOT
              id: step2
              run: |
                sudo snap install root-framework
                which root
                echo "ROOTSYS=${ROOTSYS}" >> $GITHUB_OUTPUT