name: Unit Tests
run-name: Unit tests for changes made by @${{ github.actor }}
on: [push]
permissions:
  contents: write
jobs:
    Unit-Test-Base:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Building AmpTools
              run: |
                mkdir Tutorials/Dalitz/lib
                mkdir Tutorials/Dalitz/bin
                make
                export AMPTOOLS_HOME=$(pwd)
                echo "AMPTOOLS_HOME=$AMPTOOLS_HOME" >> $GITHUB_ENV
                echo "AMPTOOLS=$AMPTOOLS_HOME/AmpTools" >> $GITHUB_ENV
                echo "AMPPLOTTER=$AMPTOOLS_HOME/AmpPlotter" >> $GITHUB_ENV
                echo "DALITZ=$AMPTOOLS_HOME/Tutorials/Dalitz" >> $GITHUB_ENV
                echo "UNIT_TESTS=$AMPTOOLS_HOME/UnitTests" >> $GITHUB_ENV
            - name: Generating Phase Space
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhaseSpace phasespace.gen.root 100000
                $DALITZ/bin/toyAcceptance phasespace.gen.root phasespace.acc.root
            - name: dalitz1
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics dalitz1.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance physics.gen.root physics.acc.root
                $DALITZ/bin/fitAmplitudes dalitz1.cfg
                $UNIT_TESTS/compare_likelihoods dalitz1.cfg
            - name: dalitz2
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics dalitz2.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance physics.gen.root physics.acc.root
                $DALITZ/bin/fitAmplitudes dalitz2.cfg
                $UNIT_TESTS/compare_likelihoods dalitz2.cfg
            - name: ConfigFileParser
              if: success() || failure()
              run: |
                cd $UNIT_TESTS
                $DALITZ/bin/generatePhaseSpace phasespace.gen.root 100000
                $DALITZ/bin/toyAcceptance phasespace.gen.root phasespace.acc.root
                $DALITZ/bin/generatePhysics parserTest.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance physics.gen.root physics.acc.root
                $DALITZ/bin/fitAmplitudes parserTest.cfg
                . parserTest
            - name: ConfigurationInfo
              if: success() || failure()
              run: . configurationInfoTest

    Unit-Test-MPI:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Building AmpTools
              run: |
                mkdir Tutorials/Dalitz/lib
                mkdir Tutorials/Dalitz/bin
                make mpi
                export AMPTOOLS_HOME=$(pwd)
                echo "AMPTOOLS_HOME=$AMPTOOLS_HOME" >> $GITHUB_ENV
                echo "AMPTOOLS=$AMPTOOLS_HOME/AmpTools" >> $GITHUB_ENV
                echo "AMPPLOTTER=$AMPTOOLS_HOME/AmpPlotter" >> $GITHUB_ENV
                echo "DALITZ=$AMPTOOLS_HOME/Tutorials/Dalitz" >> $GITHUB_ENV
                echo "UNIT_TESTS=$AMPTOOLS_HOME/UnitTests" >> $GITHUB_ENV
            - name: Generating Phase Space
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhaseSpace phasespace.gen.root 100000
                $DALITZ/bin/toyAcceptance phasespace.gen.root phasespace.acc.root
            - name: dalitz1
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics dalitz1.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance physics.gen.root physics.acc.root
                mpirun -n 3 $DALITZ/bin/fitAmplitudesMPI dalitz1.cfg
                mpirun -n 3 $UNIT_TESTS/compare_likelihoodsMPI dalitz1.cfg
            - name: dalitz2
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics dalitz2.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance physics.gen.root physics.acc.root
                mpirun -n 3 $DALITZ/bin/fitAmplitudesMPI dalitz2.cfg
                mpirun -n 3 $UNIT_TESTS/compare_likelihoodsMPI dalitz2.cfg
            - name: dalitz3
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics dalitz3.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance physics.gen.root physics.acc.root
                mpirun -n 3 $DALITZ/bin/fitAmplitudesMPI dalitz3.cfg
                mpirun -n 3 $UNIT_TESTS/compare_likelihoodsMPI dalitz3.cfg
            - name: ConfigFileParser
              if: success() || failure()
              run: |
                cd $UNIT_TESTS
                $DALITZ/bin/generatePhaseSpace phasespace.gen.root 100000
                $DALITZ/bin/toyAcceptance phasespace.gen.root phasespace.acc.root
                $DALITZ/bin/generatePhysics parserTest.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance physics.gen.root physics.acc.root
                $DALITZ/bin/fitAmplitudes parserTest.cfg
                ls
                . parserTest
            - name: ConfigurationInfo
              if: success() || failure()
              run: . configurationInfoTest
    Unit-Test-GPU:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Building AmpTools
              run: |
                mkdir Tutorials/Dalitz/lib
                mkdir Tutorials/Dalitz/bin
                make gpu
                export AMPTOOLS_HOME=$(pwd)
                echo "AMPTOOLS_HOME=$AMPTOOLS_HOME" >> $GITHUB_ENV
                echo "AMPTOOLS=$AMPTOOLS_HOME/AmpTools" >> $GITHUB_ENV
                echo "AMPPLOTTER=$AMPTOOLS_HOME/AmpPlotter" >> $GITHUB_ENV
                echo "DALITZ=$AMPTOOLS_HOME/Tutorials/Dalitz" >> $GITHUB_ENV
                echo "UNIT_TESTS=$AMPTOOLS_HOME/UnitTests" >> $GITHUB_ENV
            - name: Generating Phase Space
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhaseSpace_GPU phasespace.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU phasespace.gen.root phasespace.acc.root
            - name: dalitz1
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics_GPU dalitz1.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU physics.gen.root physics.acc.root
                $DALITZ/bin/fitAmplitudes_GPU dalitz1.cfg
                $UNIT_TESTS/compare_likelihoods_GPU dalitz1.cfg
            - name: dalitz2
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics_GPU dalitz2.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU physics.gen.root physics.acc.root
                $DALITZ/bin/fitAmplitudes_GPU dalitz2.cfg
                $UNIT_TESTS/compare_likelihoods_GPU dalitz2.cfg
            - name: dalitz3
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics_GPU dalitz3.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU physics.gen.root physics.acc.root
                $DALITZ/bin/fitAmplitudes_GPU dalitz3.cfg
                $UNIT_TESTS/compare_likelihoods_GPU dalitz3.cfg
            - name: ConfigFileParser
              if: success() || failure()
              run: |
                cd $UNIT_TESTS
                $DALITZ/bin/generatePhaseSpace_GPU phasespace.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU phasespace.gen.root phasespace.acc.root
                $DALITZ/bin/generatePhysics_GPU parserTest.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU physics.gen.root physics.acc.root
                $DALITZ/bin/fitAmplitudes_GPU parserTest.cfg
                ls
                parserTest
            - name: ConfigurationInfo
              if: success() || failure()
              run: |
                cd $UNIT_TESTS
                configurationInfoTest
          
    Unit-Test-MPI-GPU:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Building AmpTools
              run: |
                mkdir Tutorials/Dalitz/lib
                mkdir Tutorials/Dalitz/bin
                make mpigpu
                export AMPTOOLS_HOME=$(pwd)
                echo "AMPTOOLS_HOME=$AMPTOOLS_HOME" >> $GITHUB_ENV
                echo "AMPTOOLS=$AMPTOOLS_HOME/AmpTools" >> $GITHUB_ENV
                echo "AMPPLOTTER=$AMPTOOLS_HOME/AmpPlotter" >> $GITHUB_ENV
                echo "DALITZ=$AMPTOOLS_HOME/Tutorials/Dalitz" >> $GITHUB_ENV
                echo "UNIT_TESTS=$AMPTOOLS_HOME/UnitTests" >> $GITHUB_ENV
            - name: Generating Phase Space
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhaseSpace_GPU phasespace.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU phasespace.gen.root phasespace.acc.root
            - name: dalitz1
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics_GPU dalitz1.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU physics.gen.root physics.acc.root
                mpirun -n 3 $DALITZ/bin/fitAmplitudesMPI_GPU dalitz1.cfg
                mpirun -n 3 $UNIT_TESTS/compare_likelihoodsMPI_GPU dalitz1.cfg
            - name: dalitz2
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics_GPU dalitz2.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU physics.gen.root physics.acc.root
                mpirun -n 3 $DALITZ/bin/fitAmplitudesMPI_GPU dalitz2.cfg
                mpirun -n 3 $UNIT_TESTS/compare_likelihoodsMPI_GPU dalitz2.cfg
            - name: dalitz3
              if: success() || failure()
              run: |
                cd $DALITZ/run
                $DALITZ/bin/generatePhysics_GPU dalitz3.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU physics.gen.root physics.acc.root
                mpirun -n 3 $DALITZ/bin/fitAmplitudesMPI_GPU dalitz3.cfg
                mpirun -n 3 $UNIT_TESTS/compare_likelihoodsMPI_GPU dalitz3.cfg
            - name: ConfigFileParser
              if: success() || failure()
              run: |
                cd $UNIT_TESTS
                $DALITZ/bin/generatePhaseSpace_GPU phasespace.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU phasespace.gen.root phasespace.acc.root
                $DALITZ/bin/generatePhysics_GPU parserTest.cfg physics.gen.root 100000
                $DALITZ/bin/toyAcceptance_GPU physics.gen.root physics.acc.root
                $DALITZ/bin/fitAmplitudesMPI_GPU parserTest.cfg
                parserTest
            - name: ConfigurationInfo
              if: success() || failure()
              run: configurationInfoTest