name: Unit Tests
run-name: Unit tests for changes made by @${{ github.actor }}
on: [push]
permissions:
  contents: write
jobs:
    Unit-Test-Base:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install ROOT Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y binutils cmake dpkg-dev g++ gcc libssl-dev git libx11-dev libxext-dev libxft-dev libxpm-dev python3 libtbb-dev gfortran libpcre3-dev libglu1-mesa-dev libglew-dev libftgl-dev libfftw3-dev libcfitsio-dev libgraphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python3-dev python3-numpy libxml2-dev libkrb5-dev libgsl-dev qtwebengine5-dev nlohmann-json3-dev libmysqlclient-dev
            - name: Install ROOT
              run: |
                sudo snap install root-framework
                echo "ROOTSYS=$ROOTSYS">> $GITHUB_ENV
                echo "$ROOTSYS/bin" >> $GITHUB_PATH
                echo "LD_LIBRARY_PATH=$ROOTSYS/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
            - name: Building AmpTools
              run: |
                mkdir Tutorials/Dalitz/lib
                mkdir -p Tutorials/Dalitz/bin
                make
                export AMPTOOLS_HOME=$(pwd)
                echo "AMPTOOLS_HOME=$AMPTOOLS_HOME" >> $GITHUB_ENV
                echo "AMPTOOLS=$AMPTOOLS_HOME/AmpTools" >> $GITHUB_ENV
                echo "AMPPLOTTER=$AMPTOOLS_HOME/AmpPlotter" >> $GITHUB_ENV
                echo "DALITZ=$AMPTOOLS_HOME/Tutorials/Dalitz" >> $GITHUB_ENV
            - name: Running Tutorial
              run: |
                cd $DALITZ/DalitzExe
                make
                cd $DALITZ/run
                $DALITZ/DalitzExe/generatePhaseSpace phasespace.gen.root 100000
                $DALITZ/DalitzExe/plotData phasespace.gen.root plots.phasespace.gen.root
                root -l -b -q "${AMPTOOLS_HOME}/unit_tests/plot_all_histograms.C(\"plots.phasespace.gen.root\")"
                $DALITZ/DalitzExe/toyAcceptance phasespace.gen.root plots.phasespace.acc.root
                $DALITZ/DalitzExe/plotData phasespace.acc.root plots.phasespace.acc.root
                root -l -b -q "$AMPTOOLS_HOME/unit_tests/plot_all_histograms.C(\"plots.phasespace.acc.root\")"
                $DALITZ/DalitzExe/generatePhysics dalitz1.cfg physics.gen.root 100000
                $DALITZ/DalitzExe/plotData physics.gen.root plots.physics.gen.root
                root -l -b -q "$AMPTOOLS_HOME/unit_tests/plot_all_histograms.C(\"plots.physics.gen.root\")"
                $DALITZ/DalitzExe/toyAcceptance physics.gen.root physics.acc.root
                $DALITZ/DalitzExe/plotData physics.acc.root plots.physics.acc.root
                root -l -b -q "$AMPTOOLS_HOME/unit_tests/plot_all_histograms.C(\"plots.physics.acc.root\")"
                $DALITZ/DalitzExe/fitAmplitudes dalitz1.cfg
                $DALITZ/DalitzExe/plotResults dalitz1.fit dalitz1.root
                root -l -b -q "$AMPTOOLS_HOME/unit_tests/plot_overlayed_histograms.C(\"dalitz1.root\")"
                $DALITZ/DalitzExe/generatePhysics dalitz2.cfg physics.gen2.root 100000
                $DALITZ/DalitzExe/plotData physics.gen2.root plots.physics.gen2.root
                root -l -b -q "$AMPTOOLS_HOME/unit_tests/plot_all_histograms.C(\"plots.physics.gen2.root\")"
                $DALITZ/DalitzExe/toyAcceptance physics.gen2.root physics.acc2.root
                $DALITZ/DalitzExe/plotData physics.acc2.root plots.physics.acc2.root
                root -l -b -q "$AMPTOOLS_HOME/unit_tests/plot_all_histograms.C(\"plots.physics.acc2.root\")"
                $DALITZ/DalitzExe/fitAmplitudes dalitz2.cfg
                $DALITZ/DalitzExe/plotResults dalitz2.fit dalitz2.root
                root -l -b -q "$AMPTOOLS_HOME/unit_tests/plot_overlayed_histograms.C(\"dalitz2.root\")"
                $DALITZ/DalitzExe/generatePhysics dalitz3.cfg physics.gen3.root 100000
                $DALITZ/DalitzExe/plotData physics.gen3.root plots.physics.gen3.root
                root -l -b -q "$AMPTOOLS_HOME/unit_tests/plot_all_histograms.C(\"plots.physics.gen3.root\")"
                $DALITZ/DalitzExe/toyAcceptance physics.gen3.root physics.acc3.root
                $DALITZ/DalitzExe/plotData physics.acc3.root plots.physics.acc3.root
                root -l -b -q "$AMPTOOLS_HOME/unit_tests/plot_all_histograms.C(\"plots.physics.acc3.root\")"
                $DALITZ/DalitzExe/fitAmplitudes dalitz3.cfg
                $DALITZ/DalitzExe/plotResults dalitz3.fit dalitz3.root
                root -l -b -q "$AMPTOOLS_HOME/unit_tests/plot_overlayed_histograms.C(\"dalitz3.root\")"
                mv *.png $AMPTOOLS_HOME/unit_tests
            - name: Commit files
              id: commit
              run: |
                cd $AMPTOOLS_HOME
                git config --local user.email "action@github.com"
                git config --local user.name "github-actions"
                git add unit_tests
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: Unit-Tests